import{a as d,S as m,i as a}from"./assets/vendor-C2BD4WGs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const g="https://pixabay.com/api/",h="50239307-4265dc0f1525b6f9dda79b82a";function y(e){return d.get(g,{params:{key:h,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{throw t})}const n=document.querySelector(".gallery"),u=document.querySelector(".loader");Object.assign(n.style,{display:"flex",flexDirection:"row",gap:"24px",flexWrap:"wrap",justifyContent:"center",margin:"24px"});n.addEventListener("click",b);function b(e){e.target.closest(".gallery-link")&&e.preventDefault()}function L(e){const t=e.tags.split(",").slice(0,3).join(", ");return`<li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${t}" />
    </a>
    <div class="image-info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
      <p><b>Categories:</b> ${t}</p> <!-- Виводимо тільки перші три категорії -->
    </div>
  </li>`}function w(e){return e.map(L).join("")}function v(e){p();const t=w(e);n.innerHTML=t,new m(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"}).refresh()}function p(){n.innerHTML=""}function x(){u.classList.add("loader-show")}function c(){u.classList.remove("loader-show")}const f=document.querySelector(".form"),S=f.querySelector('input[name="search-text"]');f.addEventListener("submit",P);function P(e){e.preventDefault();const t=S.value.trim();if(t===""){a.error({title:"Input Error",message:"Please enter a search term!",position:"topRight"});return}p(),x(),y(t).then(i=>{if(c(),i.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(i)}).catch(()=>{c(),a.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"})})}
//# sourceMappingURL=index.js.map
